project: 
  type: website

website:
  title: "ISSS626-Geospatial Analytics"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1.1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex1.1.html"
          - text: "Hands-on Exercise 1.2"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex1.2.html"
          - text: "Hands-on Exercise 2.1"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex2.1.html"
          - text: "Hands-on Exercise 2.2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex2.2.html"            
          - text: "Hands-on Exercise 3"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"  
          - text: "Hands-on Exercise 4"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"              
          - text: "Hands-on Exercise 5.1"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex5.1.html"
          - text: "Hands-on Exercise 5.2"
            href: "Hands-on_Ex/Hands-on_Ex05/Hans-on_Ex5.2.html"
          - text: "Hands-on Exercise 6"
            href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"  
          - text: "Hands-on Exercise 7"
            href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html"  
          - text: "Hands-on Exercise 8"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html"  
          - text: "Hands-on Exercise 9"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.html"  
          - text: "Hands-on Exercise 10a"
            href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10a.html"  
          - text: "Hands-on Exercise 10b"
            href: "Hands-on_Ex/Hands-on_Ex10b/Hands-on_Ex10b.html"  

  
      - text: "In-class Exercise"
        menu:
          - text: "In-class Exercise 01"
            href: "In-class_Ex/In-class_Ex01/In-class_Ex01.qmd"          
          - text: "In-class Exercise 02"
            href: "In-class_Ex/In-class_Ex02/In-class_Ex02.qmd"
          - text: "In-class Exercise 03"
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03.qmd"
          - text: "In-class Exercise 04"
            href: "In-class_Ex/In-class_Ex04/In-class_Ex04.qmd"
          - text: "In-class Exercise 05"
            href: "In-class_Ex/In-class_Ex05/In-class_Ex05.qmd"
          - text: "In-class Exercise 06"
            href: "In-class_Ex/In-class_Ex06/In-class_Ex06.qmd"
          - text: "In-class Exercise 07"
            href: "In-class_Ex/In-class_Ex07/In-class_Ex07.qmd"
          - text: "In-class Exercise 08"
            href: "In-class_Ex/In-class_Ex8/In-class_Ex08.qmd"
          - text: "In-class Exercise 09"
            href: "In-class_Ex/In-class_Ex09/In-class_Ex09.qmd"

  
      - text: "Take-home Exercise"
        menu:
          - text: "Take-home Exercise 01"
            href: "Take-home_Ex/Take-Home_Ex01/Take-home_Ex01.html"
          - text: "Take-home Exercise 02"
            href: "Take-home_Ex/Take-Home_Ex02/Take-home_Ex02.html"
          - text: "Take-home Exercise 03"
            href: "Take-home_Ex/Take-Home_Ex03/Take-home_Ex03.html"

    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual
