project: 
  type: website

website:
  title: "ISSS626-Geospatial Analytics"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1.1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex1.1.html"
          - text: "Hands-on Exercise 1.2"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex1.2.html"
          - text: "Hands-on Exercise 2.1"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex2.1.html"
          - text: "Hands-on Exercise 2.2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex2.2.html"            
          - text: "Hands-on Exercise 3"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"  
          - text: "Hands-on Exercise 4"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"              
          - text: "Hands-on Exercise 5.1"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex5.1.html"
          - text: "Hands-on Exercise 5.2"
            href: "Hands-on_Ex/Hands-on_Ex05/Hans-on_Ex5.2.html"
          - text: "Hands-on Exercise 6"
            href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"  
          - text: "Hands-on Exercise 7"
            href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html"  
          - text: "Hands-on Exercise 8"
          - text: "Hands-on Exercise 9"
          - text: "Hands-on Exercise 10"
  
      - text: "In-class Exercise"
        menu:
          - text: "In-class Exercise 01"
            href: "In-class_Ex/In-class_Ex01/In-class_Ex01.qmd"          
          - text: "In-class Exercise 02"
            href: "In-class_Ex/In-class_Ex02/In-class_Ex02.qmd"
          - text: "In-class Exercise 03"
          - text: "In-class Exercise 04"
            href: "In-class_Ex/In-class_Ex04/In-class_Ex04.qmd"
          - text: "In-class Exercise 05"
          - text: "In-class Exercise 06"
          - text: "In-class Exercise 07"
          - text: "In-class Exercise 08"
          - text: "In-class Exercise 09"
          - text: "In-class Exercise 10"
  
      - text: "Take-home Exercise"
        menu:
          - text: "Take-home Exercise 01"
            href: "Take-home_Ex/Take-Home_Ex01/Take-home_Ex01.html"
          - text: "Take-home Exercise 02"
          - text: "Take-home Exercise 03"

    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual
